### PR TITLE
Format stat card display data, add daily/weekly offset toggle

### PR DESCRIPTION
**Pull request by galbwe**
#### What does this PR do?
Addresses [issue 14](https://github.com/codefordenver/cdphe-accessible-covid19/issues/14) and [issue 17](https://github.com/codefordenver/cdphe-accessible-covid19/issues/17)

Formats data in `StatsCard` component so that
1. Integers and decimals are comma separated.
2. Decimals are truncated to 2 decimal places.
3. NaNs and movements that will always be 0 or don't make sense for some other reason are hidden.
4. Aliases are used for abbreviated field names.

Changes the color of the movement statistic depending on context. It made more sense to me that an increase in deaths should be colored red, whereas an increase in population or number of tests should be colored green.

Adds a button that toggles the offset in the diffs between daily and weekly.

#### Where should the reviewer start?
Most relevant code for data formatting is in the `StatsCard` component. Changes to utility methods are in `utilities.js`.

Changes to add the daily/weekly toggle are in the `App` and `Home` components.

#### How should this be manually tested?
Go to the home page and check the formatting
Screen Shot 2021-01-14 at 9 42 34 PM
Then click the "Daily/Weekly" button
Screen Shot 2021-01-14 at 9 42 46 PM

#### What are the relevant tickets?
Addresses [issue 14](https://github.com/codefordenver/cdphe-accessible-covid19/issues/14) and [issue 17](https://github.com/codefordenver/cdphe-accessible-covid19/issues/17)

### CODE REVIEW

**Comment by galbwe** [comment]
@jberns this is ready for review if someone has time.

**Comment by galbwe** [comment]
Actually I need to make sure the weekly/daily toggle button doesn't show when viewing visualizations.

**Comment by galbwe** [comment]
Okay fixed that issue. Now it's ready for review.

**Review by jberns — APPROVED** [review]
This is supper awesome!  👍

**Pull request merged**
